version: '3.5'
services:
  zookeeper:
    image: zookeeper
    hostname: zookeeper
    environment:
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - "2181:2181"
      - "8080:8080"
  kafka:
    image: confluentinc/cp-kafka:5.3.1
    depends_on:
      - zookeeper
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.1.131:29092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_BROKER_ID=1
    ports:
      - "29092:29092"
  kafka-schema-registry-1:
    image: confluentinc/cp-schema-registry
    hostname: cp-schema-registry
    container_name: cp-schema-registry-1
    depends_on:
      - kafka
      - zookeeper
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
      - SCHEMA_REGISTRY_HOST_NAME=localhost
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
      - SCHEMA_REGISTRY_DEBUG=true
    ports:
      - "8081:8081"